/**
 * College Knowledge Database — Sunway College Kathmandu
 */

export const collegeData = {
  college: {
    name: "Sunway College Kathmandu",
    shortName: "Sunway",
    logo: "/assets/images/logo.png",
    description: "Sunway College Kathmandu is a premier private college affiliated with Tribhuvan University, offering quality education in Business, IT, and Social Sciences since 2007.",
    established: 2007,
    address: "Nawbise, Naikap, Kathmandu, Nepal",
    phone: "+977-01-5187600",
    email: "info@sunway.edu.np",
    admissionEmail: "admission@sunway.edu.np",
    website: "https://sunway.edu.np",
    mapUrl: "https://www.google.com/maps/place/Sunway+College+Kathmandu",
    mapEmbedUrl: "https://maps.google.com/?q=Sunway+College+Kathmandu,Naikap",
    socialLinks: {
      facebook: "https://facebook.com/sunwaycollege",
      instagram: "https://instagram.com/sunwaycollege",
      youtube: "https://youtube.com/sunwaycollege",
    },
    officeHours: "Sunday–Friday: 9:00 AM – 5:00 PM",
    tagline: "Excellence in Education, Leaders for Tomorrow",
    affiliation: "Tribhuvan University",
    accreditation: "University Grants Commission (UGC), Nepal",
  },

  courses: [
    {
      id: "bba",
      name: "Bachelor of Business Administration",
      shortName: "BBA",
      duration: "4 years (8 semesters)",
      university: "Tribhuvan University",
      description: "A comprehensive undergraduate business program covering management, marketing, finance, accounting, and entrepreneurship with an emphasis on real-world application.",
      eligibility: "10+2 or equivalent with minimum 45% marks in any stream",
      intake: "72 students per year",
      coverImage: "/assets/images/courses/bba.jpg",
      brochureUrl: "/assets/pdfs/bba-brochure.pdf",
      careerOpportunities: ["Business Manager", "Marketing Executive", "Financial Analyst", "Entrepreneur", "HR Manager", "Operations Manager"],
      highlights: ["Industry visits", "Guest lectures", "Internship program", "Business plan competitions"],
    },
    {
      id: "bca",
      name: "Bachelor of Computer Applications",
      shortName: "BCA",
      duration: "4 years (8 semesters)",
      university: "Tribhuvan University",
      description: "A four-year IT program covering programming, database systems, networking, web development, software engineering and mobile application development.",
      eligibility: "10+2 or equivalent with minimum 45% marks (any stream)",
      intake: "48 students per year",
      coverImage: "/assets/images/courses/bca.jpg",
      brochureUrl: "/assets/pdfs/bca-brochure.pdf",
      careerOpportunities: ["Software Developer", "Web Developer", "Database Administrator", "System Analyst", "IT Consultant"],
      highlights: ["Modern computer labs", "Industry partnerships", "Live projects", "Internship program"],
    },
    {
      id: "bbs",
      name: "Bachelor of Business Studies",
      shortName: "BBS",
      duration: "4 years",
      university: "Tribhuvan University",
      description: "A traditional business degree covering accounting, management, economics, and business law — ideal for students seeking careers in banking, commerce and administration.",
      eligibility: "10+2 or equivalent with minimum 45% marks",
      intake: "96 students per year",
      coverImage: "/assets/images/courses/bbs.jpg",
      brochureUrl: "/assets/pdfs/bbs-brochure.pdf",
      careerOpportunities: ["Accountant", "Bank Officer", "Business Analyst", "Tax Consultant", "Audit Associate"],
      highlights: ["CA preparation support", "Bank visit programs", "Strong alumni network"],
    },
    {
      id: "bsc-csit",
      name: "Bachelor of Science in CSIT",
      shortName: "B.Sc. CSIT",
      duration: "4 years (8 semesters)",
      university: "Tribhuvan University",
      description: "A science-based computer program with deep focus on algorithms, data structures, artificial intelligence, networking, and advanced software systems.",
      eligibility: "10+2 Science with Physics, Chemistry, Mathematics (minimum 45%)",
      intake: "48 students per year",
      coverImage: "/assets/images/courses/csit.jpg",
      brochureUrl: "/assets/pdfs/csit-brochure.pdf",
      careerOpportunities: ["Software Engineer", "AI/ML Engineer", "Data Scientist", "Network Engineer", "Research Analyst"],
      highlights: ["Advanced computing labs", "AI & Machine Learning modules", "Research projects", "Industry tie-ups"],
    },
    {
      id: "mbs",
      name: "Master of Business Studies",
      shortName: "MBS",
      duration: "2 years (4 semesters)",
      university: "Tribhuvan University",
      description: "A postgraduate management program designed for working professionals and fresh graduates aiming for senior management roles.",
      eligibility: "Bachelor's degree with minimum 45% marks",
      intake: "36 students per year",
      coverImage: "/assets/images/courses/mbs.jpg",
      brochureUrl: "/assets/pdfs/mbs-brochure.pdf",
      careerOpportunities: ["Senior Manager", "Business Consultant", "Director", "Policy Analyst"],
      highlights: ["Evening classes available", "Executive mentorship", "Live case studies"],
    },
  ],

  fees: {
    bba: {
      courseId: "bba",
      admissionFee: 20000,
      semesterFee: 35000,
      examFee: 4000,
      labFee: 0,
      totalFirstYear: 98000,
      currency: "NPR",
      note: "Fees are subject to annual revision. Scholarship available for merit students.",
      breakdown: [
        { item: "Admission Fee (One Time)", amount: 20000 },
        { item: "Semester Fee (×2 per year)", amount: 35000 },
        { item: "Exam Fee (Per Semester)", amount: 4000 },
        { item: "Student Welfare Fund", amount: 2000 },
      ],
    },
    bca: {
      courseId: "bca",
      admissionFee: 18000,
      semesterFee: 32000,
      examFee: 4000,
      labFee: 5000,
      totalFirstYear: 96000,
      currency: "NPR",
      note: "Lab fee includes computer lab access, internet and licensed software.",
      breakdown: [
        { item: "Admission Fee (One Time)", amount: 18000 },
        { item: "Semester Fee (×2 per year)", amount: 32000 },
        { item: "Exam Fee (Per Semester)", amount: 4000 },
        { item: "Lab Fee (Per Semester)", amount: 5000 },
      ],
    },
    bbs: {
      courseId: "bbs",
      admissionFee: 12000,
      semesterFee: 22000,
      examFee: 3000,
      labFee: 0,
      totalFirstYear: 62000,
      currency: "NPR",
      note: "Most affordable program. Special early-bird discount available.",
      breakdown: [
        { item: "Admission Fee (One Time)", amount: 12000 },
        { item: "Semester Fee (×2 per year)", amount: 22000 },
        { item: "Exam Fee (Per Semester)", amount: 3000 },
      ],
    },
    "bsc-csit": {
      courseId: "bsc-csit",
      admissionFee: 22000,
      semesterFee: 38000,
      examFee: 4500,
      labFee: 6000,
      totalFirstYear: 114500,
      currency: "NPR",
      note: "Includes access to advanced computing lab, cloud credits and research resources.",
      breakdown: [
        { item: "Admission Fee (One Time)", amount: 22000 },
        { item: "Semester Fee (×2 per year)", amount: 38000 },
        { item: "Exam Fee (Per Semester)", amount: 4500 },
        { item: "Lab Fee (Per Semester)", amount: 6000 },
      ],
    },
    mbs: {
      courseId: "mbs",
      admissionFee: 25000,
      semesterFee: 42000,
      examFee: 5000,
      totalFirstYear: 119000,
      currency: "NPR",
      note: "Evening batch available for working professionals.",
      breakdown: [
        { item: "Admission Fee (One Time)", amount: 25000 },
        { item: "Semester Fee (×2 per year)", amount: 42000 },
        { item: "Exam Fee (Per Semester)", amount: 5000 },
        { item: "Study Material Fee", amount: 3000 },
      ],
    },
  },

  admissions: {
    process: [
      "Fill the online or offline admission form at the college.",
      "Submit required documents for verification.",
      "Appear for entrance test (required for B.Sc. CSIT).",
      "Check merit list on college notice board or website.",
      "Complete admission by paying the fees within the deadline.",
    ],
    requiredDocuments: [
      "10+2 or equivalent marksheet and character certificate (original + 2 copies)",
      "Migration certificate (if applicable)",
      "Citizenship certificate or passport photocopy",
      "2 recent passport-size photographs",
      "Medical fitness certificate",
    ],
    deadlines: {
      fallSemester: "Mid-August (approximate — check website for exact dates)",
      springSemester: "Mid-January (approximate)",
    },
    entranceInfo: "Entrance exam required for B.Sc. CSIT. BBA, BCA and BBS admit based on merit.",
    admissionFormUrl: "/admission",
    contactPhone: "+977-01-5187600",
    contactEmail: "admission@sunway.edu.np",
  },

  scholarships: [
    {
      id: "merit-scholarship",
      name: "Merit Scholarship",
      eligibility: "Students scoring 80% or above in 10+2",
      amount: "20–30% fee waiver on semester fees",
      description: "Awarded to academically outstanding students. Renewable each semester based on academic performance.",
      renewable: true,
      renewalCriteria: "Maintain CGPA 3.6 or above",
    },
    {
      id: "sports-scholarship",
      name: "Sports Excellence Scholarship",
      eligibility: "National or provincial level sports players",
      amount: "Up to 25% fee waiver",
      description: "Supports talented athletes who represent Nepal at national or provincial level.",
      renewable: true,
    },
    {
      id: "need-based",
      name: "Need-Based Financial Aid",
      eligibility: "Students from low-income families with good academic record",
      amount: "Up to 50% fee waiver",
      description: "Income-based support for deserving students. Requires income certificate and academic record.",
      renewable: true,
    },
    {
      id: "sibling",
      name: "Sibling Concession",
      eligibility: "Siblings of currently enrolled students",
      amount: "10% discount on semester fees",
      description: "Special concession for families with two or more children enrolled at Sunway College.",
      renewable: false,
    },
    {
      id: "early-bird",
      name: "Early Admission Discount",
      eligibility: "Students who complete admission in first 2 weeks of admission open",
      amount: "NPR 5,000 off on admission fee",
      description: "One-time discount for early applicants.",
      renewable: false,
    },
  ],

  faculty: [
    {
      id: "principal",
      name: "Prof. Dr. Ramesh Raj Pant",
      designation: "Principal",
      department: "Administration",
      photo: "/assets/images/faculty/principal.jpg",
      bio: "Ph.D. in Management from Tribhuvan University. Over 22 years of academic leadership experience. Former Dean of Management at TU.",
      email: "principal@sunway.edu.np",
    },
    {
      id: "hod-bba",
      name: "Prof. Anita Shrestha",
      designation: "Head of Department – BBA",
      department: "Business Administration",
      photo: "/assets/images/faculty/hod-bba.jpg",
      bio: "MBA from Asian Institute of Technology, Thailand. Expert in Strategic Management and Marketing. 14 years teaching experience.",
      email: "hod.bba@sunway.edu.np",
    },
    {
      id: "hod-it",
      name: "Prof. Bikash Karmacharya",
      designation: "Head of Department – IT",
      department: "Information Technology",
      photo: "/assets/images/faculty/hod-it.jpg",
      bio: "M.Sc. in Computer Science. Specializes in Software Engineering and Machine Learning. Industry experience of 10 years.",
      email: "hod.it@sunway.edu.np",
    },
    {
      id: "hod-bbs",
      name: "Prof. Suman Khanal",
      designation: "Head of Department – BBS",
      department: "Business Studies",
      photo: "/assets/images/faculty/hod-bbs.jpg",
      bio: "M.Com from TU. Specialist in Accounting, Auditing and Taxation. 16 years of teaching and industry experience.",
      email: "hod.bbs@sunway.edu.np",
    },
  ],

  facilities: {
    library: {
      id: "library",
      title: "Central Library",
      description: "Sunway College library spans over 3,500 sq ft with 20,000+ books, journals, e-resources and a dedicated digital reading section. Open Sunday–Friday 8AM–6PM.",
      coverImage: "/assets/images/facilities/library.jpg",
      panoramaUrl: "/assets/360/library.jpg",
      gallery: ["/assets/images/facilities/library-1.jpg"],
      highlights: ["20,000+ books and journals", "Digital library access", "Quiet reading rooms", "E-resource access"],
    },
    computerLab: {
      id: "computerLab",
      title: "Computer Laboratory",
      description: "State-of-the-art computer labs with 150+ high-spec workstations, 1 Gbps fibre internet, and industry-standard software including Visual Studio, AutoCAD, SPSS and more.",
      coverImage: "/assets/images/facilities/computer-lab.jpg",
      panoramaUrl: "/assets/360/computer-lab.jpg",
      gallery: [],
      highlights: ["150+ workstations", "1 Gbps internet", "24/7 lab access for projects", "Licensed software suite"],
    },
    cafeteria: {
      id: "cafeteria",
      title: "Student Cafeteria",
      description: "Clean, affordable cafeteria serving Nepali, Indian and continental meals. Seating for 200+ students with a hygienic kitchen.",
      coverImage: "/assets/images/facilities/cafeteria.jpg",
      highlights: ["Affordable pricing", "Hygienic standards", "Vegetarian & non-veg options", "Snack corner"],
    },
    sports: {
      id: "sports",
      title: "Sports Facilities",
      description: "Spacious outdoor grounds for cricket and football, indoor badminton courts, table tennis room and a well-equipped gymnasium.",
      coverImage: "/assets/images/facilities/sports.jpg",
      highlights: ["Cricket & football ground", "Indoor badminton", "Table tennis", "Gymnasium"],
    },
    auditorium: {
      id: "auditorium",
      title: "Auditorium",
      description: "600-seat modern auditorium fully equipped with audio-visual systems, used for seminars, conferences, cultural programs and convocations.",
      coverImage: "/assets/images/facilities/auditorium.jpg",
      panoramaUrl: "/assets/360/auditorium.jpg",
      highlights: ["600-seat capacity", "Full AV setup", "Air-conditioned", "Stage with backstage"],
    },
    hostel: {
      id: "hostel",
      title: "Hostel",
      description: "Separate hostel facilities for boys and girls with fully furnished rooms, meals, Wi-Fi and 24/7 security — located within walking distance of the college.",
      coverImage: "/assets/images/facilities/hostel.jpg",
      highlights: ["Boys & girls separate", "Meals included", "Wi-Fi", "24/7 security"],
    },
  },

  faqs: [
    {
      id: "faq-1",
      question: "What is the admission deadline for BBA?",
      answer: "BBA admission typically opens in July and closes in mid-August. Please check the college website or call +977-01-5187600 for exact dates.",
      category: "admissions",
    },
    {
      id: "faq-2",
      question: "Is hostel facility available at Sunway College?",
      answer: "Yes, Sunway College has separate hostel facilities for boys and girls near the campus. Please contact the admission office for current hostel fees and availability.",
      category: "facilities",
    },
    {
      id: "faq-3",
      question: "Which university is Sunway College affiliated with?",
      answer: "Sunway College Kathmandu is affiliated with Tribhuvan University (TU), Nepal's largest and most recognized university.",
      category: "general",
    },
    {
      id: "faq-4",
      question: "Does Sunway College offer placement services?",
      answer: "Yes, our Career Development Center assists students with internships, CV building, mock interviews and job placements through our industry partners.",
      category: "careers",
    },
    {
      id: "faq-5",
      question: "Can I pay fees in installments?",
      answer: "Yes, semester fee payment can be split into two installments. Please speak with the Accounts Department for the installment schedule.",
      category: "fees",
    },
    {
      id: "faq-6",
      question: "Is there an entrance exam for BCA?",
      answer: "BCA admission is merit-based (no entrance exam). B.Sc. CSIT requires an entrance examination. BBA and BBS are also merit-based.",
      category: "admissions",
    },
    {
      id: "faq-7",
      question: "What is the medium of instruction?",
      answer: "The medium of instruction at Sunway College is English for all programs.",
      category: "general",
    },
  ],

  contact: {
    phone: "+977-01-5187600",
    alternatePhone: "+977-9851234567",
    email: "info@sunway.edu.np",
    admissionEmail: "admission@sunway.edu.np",
    address: "Nawbise, Naikap, Kathmandu, Nepal",
    officeHours: "Sunday–Friday: 9:00 AM – 5:00 PM",
    mapEmbedUrl: "https://maps.google.com/?q=Sunway+College+Kathmandu",
    socialLinks: {
      facebook: "https://facebook.com/sunwaycollege",
      instagram: "https://instagram.com/sunwaycollege",
      youtube: "https://youtube.com/sunwaycollege",
    },
  },
};

export const leadsStore = [];
export default collegeData;
